### ISSUE TITLE
Need to implement the TiDE model

### ISSUE THREAD

**Issue by joshua-xia** [sktime/pytorch-forecasting#1337]
Paper: https://arxiv.org/abs/2304.08424
Blog: https://ai.googleblog.com/2023/04/recent-advances-in-deep-long-horizon.html
Google research implement: https://github.com/google-research/google-research/tree/master/tide

**Comment by Sohaib-Ahmed21** [comment]
I have started work on this. @fkiraly kindly assign me this issue.
