### ISSUE TITLE
[MNT] readthedocs build preview in CI

### ISSUE THREAD

**Issue by fkiraly** [sktime/pytorch-forecasting#1708]
We should replace the "build" CI step with a full documentation preview from readthedocs, which allows to view the built documentation in the browser.

This should be as in `sktime` .

Suggested by @yarnabrina. I have forgotten how to set this up though, you do this once per repo, and maybe it was not me who set it up...

@yarnabrina, @julian-fong, do you know how to enable this?

**Comment by yarnabrina** [comment]
It should be possible by the admin, so you (and may be CC? not sure). The steps are documented [here](https://docs.readthedocs.io/en/stable/guides/pull-requests.html).

![image](https://github.com/user-attachments/assets/8f21dd59-e9fd-4042-98c2-83d5c55615a1)

**Comment by fkiraly** [comment]
ok, I have tried this.

Re current state, FYI: only I and @jdb78 are admins for the readthedocs. We need to figure out the governance structure for individual projects under the umbrella and how asset ownership relates to the incorporations. We are setting up a working group for this, now that the German umbrella is operational.

**Comment by fkiraly** [comment]
Works, tested in #1712.
